### ISSUE TITLE
[Design] wallet-desktop: new interface for holdings price

### ISSUE THREAD

**Issue by tuliomir** [HathorNetwork/hathor-wallet#342]
We should define a user-friendly way to display the current price of HTR and any custom tokens that have a public price, along with the total value of each holding.

**Comment by TalisGalhardi** [comment]
For this issue, I have designed a panel that shows the current tokens value right next to the screen title, as follows:

Display HTR Tokens Value:
![DESKTOP   GITHUB #342  Custom Token Value](https://user-images.githubusercontent.com/111133889/187216594-14dc6327-522c-476f-b968-122ba8902d4c.png)

Display Custom Tokens Value:
![DESKTOP   GITHUB #342  HTR Value](https://user-images.githubusercontent.com/111133889/187216602-d298cbae-d16a-4417-9529-7cd93d7fe6ae.png)

I sought to create something simple and that from my point of view requires less development, using the following arguments:
1. Consistency and Standards - Use what we already have;
2. Aesthetic and minimalist design - The addition needs to be discreet and clear;
3. Approaching Design Refactor - There is no need to create something too elaborate due to an imminent wallet redesign.

The prototype link: https://www.figma.com/file/dr4pwNgvpf5vXnIiln7KX5/Wallet?node-id=2%3A16607
PDF File: 
[[GITHUB #342] [DESKTOP] Token's Value.pdf](https://github.com/HathorNetwork/hathor-wallet/files/9445107/GITHUB.342.DESKTOP.Token.s.Value.pdf)

@msbrogli and @Trond please let me know if you have any doubts or suggestions.

**Comment by msbrogli** [comment]
@trondbjoroy

**Comment by trondbjoroy** [comment]
@TalisGalhardi @tuliomir I like how the token price is shown, but I couldn't see the total value of each holding anywhere?

I also think this should be a feature that can be toggled on/off as portfolio value is quite private information that you don't always want others to see.

**Comment by msbrogli** [comment]
@TalisGalhardi My comment is exactly the same as Trond's. I have nothing else to add.

**Comment by TalisGalhardi** [comment]
@msbrogli @trondbjoroy

Here's the prototype's link with my proposition, adding your suggestions:
https://www.figma.com/proto/nwwwjlgNRayzpaZztnvaqF/Hathor-Prototypes?page-id=798%3A19238&node-id=798%3A19240&viewport=648%2C1013%2C0.06&scaling=scale-down&starting-point-node-id=798%3A19240

![image](https://user-images.githubusercontent.com/111133889/187470417-2f939d7f-eb75-4d07-a2f2-715902744306.png)
![image](https://user-images.githubusercontent.com/111133889/187470458-c01c402f-4ad2-4bb5-87f6-2e63f272a1d2.png)
![image](https://user-images.githubusercontent.com/111133889/187470491-a52dd28c-309d-4cb8-a1b6-0067ea3bdf84.png)

**Comment by trondbjoroy** [comment]
@TalisGalhardi As we discussed, I like this suggestion and the design is approved by me.

**Comment by tuliomir** [comment]
:heavy_check_mark: Approved by me as well

**Comment by msbrogli** [comment]
@TalisGalhardi @trondbjoroy @tuliomir When user toggles to show the price, should we show the price also in the transaction history?

**Comment by trondbjoroy** [comment]
> @TalisGalhardi @trondbjoroy @tuliomir When user toggles to show the price, should we show the price also in the transaction history?

Personally, I don't see that adding much value. For historical prices and portfolio value over time, Talis has a suggestion for this in the wallet redesign.

**Comment by msbrogli** [comment]
Ok. Nothing else to add and this design is approved by me as well.
