### ISSUE TITLE
Spike: Wallet gets too slow to use when there are many transactions

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet#96]
We have a user report that the wallet is freezing after sending a transaction.

This issue is to discover when the freeze happens, in what conditions and how to solve it.

One problem that might be causing it is the number of transactions in the storage.

**Comment by pedroferreira1** [comment]
Wallet test executed with 30k transactions.

Send tokens: normal
Generate new address: normal
See history: normal
Create new token: normal

The wallet gets slow / freezes when receives a new transactions and has to do the data update. The update for the new transaction was taking around 2-4 seconds and in the meantime the wallet was frozen.

The costly part of the real time update is that we filter the full history to show the transactions of the selected token and we also sort by timestamp, so we can show the history in the correct order. 

I've sent a new transaction and received 18 events of new_history in the wallet. For this reason, executing the real time update 18 times in a history of 30k transactions is freezing the wallet for 2-4 seconds every time.

We should try to remove the repeated events arrived from the server, or handle them in the wallet, only executing the unique ones. This would already make the wallet works without freezing until around 100k transactions at least.

After that we should start thinking about not sorting the history in the frontend (at least not in real time).

**Comment by obiyankenobi** [comment]
We can try to filter repeated events on the lib and only emit "new" ones.

I also wonder if we can improve our algorithm for sorting the txs.

**Comment by pedroferreira1** [comment]
About the events, filtering them in the lib is a big hack in my opinion. I think we should try to fix it in the full node.

About the sorting, we do this every time we receive a new tx because they might arrive in a wrong order but we could sort like the 100 first, because it's hard to receive a new tx and we already have 100 newer. Maybe this 100 number could depend on the tx rate the wallet is receiving, so if we receive 1 tx/s this number could be 100 and if it's 10 tx/s could be 1000, don't know. But there are ways we could reduce the work done there.

**Comment by msbrogli** [comment]
Regarding the events, I agree that we should fix it in the full node. In fact, the event bus in the full node deserves a full refactor.

Regarding the sorting, assuming that the history is sorted, we can just sort the received transactions and merge in `O(n+m)` instead of appending and sorting the whole array, where `n` is the number of transactions in the history and `m` s the number of received transactions.

As usually the received transaction have bigger timestamp, they would be added to the front of the list, which is slow. So, we can reverse sort the history, and we would be able to just append the new transaction to the end of the list.

I think we can create these two issues and close this spike. Well done!

**Comment by pedroferreira1** [comment]
Created both issues, so closing the Spike now.
